# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd0647f09f68f6f0f0423eabb5bd1f79208b71fabb886984f6cb7418c7b42719de3399a338494cd6ba937ab06d4167774c9522c83d13eee0c50ae2b7b5d46770

test:
  secret_key_base: e35f4c2cf37f373611c33e2238c151846f284f39dec40f7165e0e378696714c54c60c87398a740e4c1261e6bc4b19379fc493e931d76f710f47c727a115fde20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
